services:
  postgres:
    image: postgres:16
    container_name: mediconnect-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mediconnect_db
      POSTGRES_USER: mediconnect_user
      POSTGRES_PASSWORD: mediconnect_pass
    volumes:
      - mediconnect_postgres_data:/var/lib/postgresql/data

  grafana-lgtm:
    image: grafana/otel-lgtm:latest
    container_name: mediconnect-lgtm
    ports:
      - "3001:3000"
      - "4317:4317"
      - "4318:4318"

volumes:
  mediconnect_postgres_data:
    name: mediconnect_postgres_data