spring.application.name=mediconnect

logging.pattern.console=${CONSOLE_LOG_PATTERN:%clr(%d{HH:mm:ss.SSS}){green} %clr(%-5level){blue} %clr([%thread]){red} %clr(%logger{20}){yellow} - %clr(%msg){cyan}%n}

# PostgreSQL Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/mediconnect_db
spring.datasource.username=mediconnect_user
spring.datasource.password=mediconnect_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${FORMAT_SQL:true}
spring.jpa.open-in-view=false

# SQL init
#spring.sql.init.mode=always

#Docker
spring.docker.compose.lifecycle-management=start-and-stop
spring.docker.compose.start.command=up
spring.docker.compose.stop.command=stop

#Jwt
mediconnect.jwt.secret=${JWT_SECRET:mediconnect-dev-secret-key-should-be-at-least-32-characters-long}
mediconnect.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

